(TeX-add-style-hook "ldhw"
 (lambda ()
    (LaTeX-add-labels
     "eq:svm:p"
     "eq:svm:d"
     "eq:kkt"
     "eq:svm:soft-margin"
     "eq:svm:hinge"
     "fig:1"
     "sec:a:code")
    (TeX-run-style-hooks
     "matlab-prettifier"
     "framed"
     "numbered"
     "dsfont"
     "eucal"
     "mathcal"
     "booktabs"
     "subcaption"
     "graphicx"
     "bm"
     "enumitem"
     "url"
     "mathtools"
     "moreenum"
     "amsthm"
     "amssymb"
     "amsmath"
     ""
     "fontenc"
     "T1"
     "latex2e"
     "art10"
     "article"
     "a4paper"
     "lddef")))

